version: '3.8'

services:
  autom4btag:
    image: ghcr.io/adipper69/autom4btag:latest
    container_name: autom4btag
    restart: unless-stopped
    volumes:
      - /volume1/Books/Audiobooks/untagged:/data/untagged
      - /volume1/Books/Audiobookshelf/Audiobooks:/data/output
      - /volume1/Books/Audiobooks/fix:/data/fix
    dns:
      - 1.1.1.1
      - 8.8.8.8
    network_mode: bridge